ALTER TABLE "receipt_photos" ALTER COLUMN "storage_path" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "attendance" ADD COLUMN "row_seq" bigint NOT NULL GENERATED ALWAYS AS IDENTITY (sequence name "attendance_row_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "audit_log" ADD COLUMN "row_seq" bigint NOT NULL GENERATED ALWAYS AS IDENTITY (sequence name "audit_log_row_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "bank_deposits" ADD COLUMN "row_seq" bigint NOT NULL GENERATED ALWAYS AS IDENTITY (sequence name "bank_deposits_row_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "beneficiaries" ADD COLUMN "row_seq" bigint NOT NULL GENERATED ALWAYS AS IDENTITY (sequence name "beneficiaries_row_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "branches" ADD COLUMN "row_seq" bigint NOT NULL GENERATED ALWAYS AS IDENTITY (sequence name "branches_row_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "cash_accounts" ADD COLUMN "row_seq" bigint NOT NULL GENERATED ALWAYS AS IDENTITY (sequence name "cash_accounts_row_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "cash_transactions" ADD COLUMN "row_seq" bigint NOT NULL GENERATED ALWAYS AS IDENTITY (sequence name "cash_transactions_row_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "collections" ADD COLUMN "row_seq" bigint NOT NULL GENERATED ALWAYS AS IDENTITY (sequence name "collections_row_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "commissions" ADD COLUMN "row_seq" bigint NOT NULL GENERATED ALWAYS AS IDENTITY (sequence name "commissions_row_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "copy_exceptions" ADD COLUMN "row_seq" bigint NOT NULL GENERATED ALWAYS AS IDENTITY (sequence name "copy_exceptions_row_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "daily_audits" ADD COLUMN "row_seq" bigint NOT NULL GENERATED ALWAYS AS IDENTITY (sequence name "daily_audits_row_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "employee_branches" ADD COLUMN "row_seq" bigint NOT NULL GENERATED ALWAYS AS IDENTITY (sequence name "employee_branches_row_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "employees" ADD COLUMN "row_seq" bigint NOT NULL GENERATED ALWAYS AS IDENTITY (sequence name "employees_row_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "expenses" ADD COLUMN "row_seq" bigint NOT NULL GENERATED ALWAYS AS IDENTITY (sequence name "expenses_row_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "fidelity" ADD COLUMN "row_seq" bigint NOT NULL GENERATED ALWAYS AS IDENTITY (sequence name "fidelity_row_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "holidays" ADD COLUMN "row_seq" bigint NOT NULL GENERATED ALWAYS AS IDENTITY (sequence name "holidays_row_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "leave_requests" ADD COLUMN "row_seq" bigint NOT NULL GENERATED ALWAYS AS IDENTITY (sequence name "leave_requests_row_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "member_programs" ADD COLUMN "row_seq" bigint NOT NULL GENERATED ALWAYS AS IDENTITY (sequence name "member_programs_row_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "member_transfers" ADD COLUMN "row_seq" bigint NOT NULL GENERATED ALWAYS AS IDENTITY (sequence name "member_transfers_row_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "members" ADD COLUMN "row_seq" bigint NOT NULL GENERATED ALWAYS AS IDENTITY (sequence name "members_row_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "monthly_audits" ADD COLUMN "row_seq" bigint NOT NULL GENERATED ALWAYS AS IDENTITY (sequence name "monthly_audits_row_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "pay_profiles" ADD COLUMN "row_seq" bigint NOT NULL GENERATED ALWAYS AS IDENTITY (sequence name "pay_profiles_row_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "payroll_adjustments" ADD COLUMN "row_seq" bigint NOT NULL GENERATED ALWAYS AS IDENTITY (sequence name "payroll_adjustments_row_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "payroll_lines" ADD COLUMN "row_seq" bigint NOT NULL GENERATED ALWAYS AS IDENTITY (sequence name "payroll_lines_row_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "payroll_runs" ADD COLUMN "row_seq" bigint NOT NULL GENERATED ALWAYS AS IDENTITY (sequence name "payroll_runs_row_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "program_categories" ADD COLUMN "row_seq" bigint NOT NULL GENERATED ALWAYS AS IDENTITY (sequence name "program_categories_row_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "program_incentives" ADD COLUMN "row_seq" bigint NOT NULL GENERATED ALWAYS AS IDENTITY (sequence name "program_incentives_row_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "programs" ADD COLUMN "row_seq" bigint NOT NULL GENERATED ALWAYS AS IDENTITY (sequence name "programs_row_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "receipt_photos" ADD COLUMN "row_seq" bigint NOT NULL GENERATED ALWAYS AS IDENTITY (sequence name "receipt_photos_row_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "receipt_photos" ADD COLUMN "chunk_count" integer;--> statement-breakpoint
ALTER TABLE "receipt_photos" ADD COLUMN "photo_data_1" text;--> statement-breakpoint
ALTER TABLE "receipt_photos" ADD COLUMN "photo_data_2" text;--> statement-breakpoint
ALTER TABLE "receipt_photos" ADD COLUMN "photo_data_3" text;--> statement-breakpoint
ALTER TABLE "receipt_photos" ADD COLUMN "photo_data_4" text;--> statement-breakpoint
ALTER TABLE "record_corrections" ADD COLUMN "row_seq" bigint NOT NULL GENERATED ALWAYS AS IDENTITY (sequence name "record_corrections_row_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "remittance_collections" ADD COLUMN "row_seq" bigint NOT NULL GENERATED ALWAYS AS IDENTITY (sequence name "remittance_collections_row_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "remittance_methods" ADD COLUMN "row_seq" bigint NOT NULL GENERATED ALWAYS AS IDENTITY (sequence name "remittance_methods_row_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "remittances" ADD COLUMN "row_seq" bigint NOT NULL GENERATED ALWAYS AS IDENTITY (sequence name "remittances_row_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "report_notes" ADD COLUMN "row_seq" bigint NOT NULL GENERATED ALWAYS AS IDENTITY (sequence name "report_notes_row_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "report_remarks" ADD COLUMN "row_seq" bigint NOT NULL GENERATED ALWAYS AS IDENTITY (sequence name "report_remarks_row_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "roles" ADD COLUMN "row_seq" bigint NOT NULL GENERATED ALWAYS AS IDENTITY (sequence name "roles_row_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "sales" ADD COLUMN "row_seq" bigint NOT NULL GENERATED ALWAYS AS IDENTITY (sequence name "sales_row_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "system_settings" ADD COLUMN "row_seq" bigint NOT NULL GENERATED ALWAYS AS IDENTITY (sequence name "system_settings_row_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "user_roles" ADD COLUMN "row_seq" bigint NOT NULL GENERATED ALWAYS AS IDENTITY (sequence name "user_roles_row_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "row_seq" bigint NOT NULL GENERATED ALWAYS AS IDENTITY (sequence name "users_row_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "vendor_payables" ADD COLUMN "row_seq" bigint NOT NULL GENERATED ALWAYS AS IDENTITY (sequence name "vendor_payables_row_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "weekly_audits" ADD COLUMN "row_seq" bigint NOT NULL GENERATED ALWAYS AS IDENTITY (sequence name "weekly_audits_row_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "yearly_audits" ADD COLUMN "row_seq" bigint NOT NULL GENERATED ALWAYS AS IDENTITY (sequence name "yearly_audits_row_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);