"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { Button } from "@/components/ui/button"; import { Card,CardContent,CardHeader,CardTitle } from "@/components/ui/card"; import { Input } from "@/components/ui/input"; import { Label } from "@/components/ui/label";
type Payable={id:string;invoiceDate:string;dueDate:string;vendor:string;category:string;description:string;amount:number;amountPaid:number;balance:number;branch:string;status:string;referenceNumber:string;remarks:string;paymentAccount:string};
type Options={branches:Array<{id:string;name:string;territory:string}>;accounts:Array<{id:string;name:string;status:string}>};
const today=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Manila"}).format(new Date()),money=(v:number)=>new Intl.NumberFormat("en-PH",{style:"currency",currency:"PHP"}).format(v);
export default function VendorPayablesPage(){const [rows,setRows]=useState<Payable[]>([]),[options,setOptions]=useState<Options>({branches:[],accounts:[]}),[show,setShow]=useState(false),[busy,setBusy]=useState(true),[message,setMessage]=useState(""),[error,setError]=useState(""),[paying,setPaying]=useState<Payable|null>(null),[payment,setPayment]=useState(""),[account,setAccount]=useState("");const [form,setForm]=useState({invoiceDate:today(),dueDate:today(),vendor:"",category:"",description:"",amount:"",branch:"",referenceNumber:"",remarks:""});
async function load(){setBusy(true);try{const [a,b]=await Promise.all([fetch("/api/vendor-payables",{cache:"no-store"}),fetch("/api/finance-options",{cache:"no-store"})]),[x,y]=await Promise.all([a.json(),b.json()]);if(!a.ok)throw new Error(x.message);if(!b.ok)throw new Error(y.message);setRows(x.payables??[]);setOptions(y);}catch(e){setError(e instanceof Error?e.message:"Unable to load payables.");}finally{setBusy(false);}}useEffect(()=>{void load();},[]);
const totals=useMemo(()=>({outstanding:rows.filter(x=>x.status!=="Paid").reduce((s,x)=>s+x.balance,0),overdue:rows.filter(x=>x.status!=="Paid"&&x.dueDate<today()).reduce((s,x)=>s+x.balance,0)}),[rows]);
async function save(e:FormEvent){e.preventDefault();setBusy(true);try{const r=await fetch("/api/vendor-payables",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,amount:Number(form.amount)})}),j=await r.json();if(!r.ok)throw new Error(j.message);setShow(false);setMessage(`Payable ${j.id} created.`);await load();}catch(x){setError(x instanceof Error?x.message:"Unable to save payable.");}finally{setBusy(false);}}
async function recordPayment(){if(!paying)return;setBusy(true);try{const r=await fetch("/api/vendor-payables",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:paying.id,amount:Number(payment),account})}),j=await r.json();if(!r.ok)throw new Error(j.message);setPaying(null);setPayment("");setAccount("");setMessage("Vendor payment recorded.");await load();}catch(x){setError(x instanceof Error?x.message:"Unable to record payment.");}finally{setBusy(false);}}
return <section className="mx-auto max-w-7xl space-y-6"><Header title="Vendor Payables" subtitle="Track funeral suppliers and larger vendor obligations separately from operating expenses." action={<Button onClick={()=>setShow(v=>!v)}>Add Payable</Button>}/>{error&&<Notice value={error}/>} {message&&<Notice value={message}/>}<div className="grid gap-4 sm:grid-cols-3"><Metric label="Outstanding" value={money(totals.outstanding)}/><Metric label="Overdue" value={money(totals.overdue)}/><Metric label="Open vendors" value={String(new Set(rows.filter(x=>x.balance>0).map(x=>x.vendor)).size)}/></div>
{show&&<Card><CardHeader><CardTitle>New Vendor Payable</CardTitle></CardHeader><CardContent><form onSubmit={save} className="grid gap-4 md:grid-cols-2 lg:grid-cols-4"><Field label="Invoice date"><Input type="date" value={form.invoiceDate} onChange={e=>setForm({...form,invoiceDate:e.target.value})}/></Field><Field label="Due date"><Input type="date" value={form.dueDate} onChange={e=>setForm({...form,dueDate:e.target.value})}/></Field><Field label="Vendor"><Input value={form.vendor} onChange={e=>setForm({...form,vendor:e.target.value})}/></Field><Field label="Category"><select className="h-9 w-full rounded-md border bg-background px-3" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option value="">Select</option>{["Casket Purchases","Embalming Supplies","Hearse Fuel","Flowers","Cemetery Fees","Funeral Services","Other"].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Amount"><Input type="number" min="0.01" step="0.01" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></Field><Field label="Branch"><select className="h-9 w-full rounded-md border bg-background px-3" value={form.branch} onChange={e=>setForm({...form,branch:e.target.value})}><option value="">Select branch</option>{options.branches.map(x=><option key={x.id} value={x.name}>{x.name} · {x.territory}</option>)}</select></Field><Field label="Reference"><Input value={form.referenceNumber} onChange={e=>setForm({...form,referenceNumber:e.target.value})}/></Field><Field label="Description"><Input value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></Field><div className="lg:col-span-4"><Button type="submit" disabled={busy}>Save Payable</Button></div></form></CardContent></Card>}
{paying&&<Card className="border-violet-60"><CardHeader><CardTitle>Pay {paying.vendor}</CardTitle></CardHeader><CardContent className="grid gap-4 sm:grid-cols-3"><Field label={`Amount (balance ${money(paying.balance)})`}><Input type="number" max={paying.balance} step="0.01" value={payment} onChange={e=>setPayment(e.target.value)}/></Field><Field label="Cash account"><select className="h-9 w-full rounded-md border bg-background px-3" value={account} onChange={e=>setAccount(e.target.value)}><option value="">Select account</option>{options.accounts.filter(x=>x.status==="active").map(x=><option key={x.id}>{x.name}</option>)}</select></Field><div className="flex items-end gap-2"><Button disabled={!payment||!account||busy} onClick={()=>void recordPayment()}>Confirm Payment</Button><Button variant="outline" onClick={()=>setPaying(null)}>Cancel</Button></div></CardContent></Card>}
<Card><CardHeader><CardTitle>Payables Register</CardTitle></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full min-w-[950px] text-sm"><thead><tr>{["Due","Vendor","Category","Branch","Total","Paid","Balance","Status","Action"].map(x=><th className="border-b p-3 text-left" key={x}>{x}</th>)}</tr></thead><tbody>{rows.map(x=><tr key={x.id}><td className="border-b p-3">{x.dueDate}</td><td className="border-b p-3"><b>{x.vendor}</b><br/><span className="text-xs">{x.description}</span></td><td className="border-b p-3">{x.category}</td><td className="border-b p-3">{x.branch}</td><td className="border-b p-3">{money(x.amount)}</td><td className="border-b p-3">{money(x.amountPaid)}</td><td className="border-b p-3 font-bold">{money(x.balance)}</td><td className="border-b p-3">{x.status}</td><td className="border-b p-3">{x.balance>0&&<Button size="sm" variant="outline" onClick={()=>setPaying(x)}>Record payment</Button>}</td></tr>)}</tbody></table></div></CardContent></Card></section>}
function Header({title,subtitle,action}:{title:string;subtitle:string;action:React.ReactNode}){return <header className="flex items-end justify-between rounded-3xl page-hero p-5"><div><span className="text-xs font-bold uppercase">Finance</span><h1 className="text-3xl font-black">{title}</h1><p className="text-sm text-violet-30/80">{subtitle}</p></div>{action}</header>}function Metric({label,value}:{label:string;value:string}){return <Card><CardContent className="pt-5"><p className="text-xs text-muted-foreground">{label}</p><p className="text-2xl font-bold">{value}</p></CardContent></Card>}function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="space-y-2"><Label>{label}</Label>{children}</div>}function Notice({value}:{value:string}){return <p className="rounded-xl border bg-muted/30 p-3 text-sm">{value}</p>}
