"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { Button } from "@/components/ui/button";
import { todayInManila } from "@/lib/account-rules";

type Kind = "daily" | "weekly" | "monthly" | "yearly";
type Line = { date: string; branch: string; programId: string; programName: string; person: string; role: string; accounts: number; gross: number; incentives: number; fidelity: number; net: number; expectedRemittance: number };
type Report = { from: string; to: string; generatedAt: string; generatedBy: string; options: { branches: string[]; programs: Array<{ id: string; name: string }>; people: string[] }; sales: Line[]; collections: Line[]; byDay: Line[]; byBranch: Line[]; byProgram: Line[]; summary: Record<string, number>; notes: string[] };
const money = (value: number) => new Intl.NumberFormat("en-PH", { style: "currency", currency: "PHP" }).format(value || 0);
const iso = (date: Date) => date.toISOString().slice(0, 10);
function range(kind: Kind, anchor: string) {
  const date = new Date(`${anchor.length === 4 ? `${anchor}-01-01` : anchor.length === 7 ? `${anchor}-01` : anchor}T00:00:00Z`);
  if (kind === "daily") return [iso(date), iso(date)];
  if (kind === "weekly") { const day = date.getUTCDay() || 7; const from = new Date(date); from.setUTCDate(date.getUTCDate() - day + 1); const to = new Date(from); to.setUTCDate(from.getUTCDate() + 6); return [iso(from), iso(to)]; }
  if (kind === "monthly") return [`${anchor}-01`, iso(new Date(Date.UTC(date.getUTCFullYear(), date.getUTCMonth() + 1, 0)))];
  return [`${anchor}-01-01`, `${anchor}-12-31`];
}
const inputType = (kind: Kind) => kind === "monthly" ? "month" : kind === "yearly" ? "number" : "date";
const defaultAnchor = (kind: Kind) => { const today = todayInManila(); return kind === "monthly" ? today.slice(0, 7) : kind === "yearly" ? today.slice(0, 4) : today; };
const csv = (value: unknown) => `"${String(value ?? "").replace(/^[=+@-]/, "'$&").replaceAll('"', '""')}"`;

export function OperationalReport({ kind }: { kind: Kind }) {
  const [anchor, setAnchor] = useState(() => defaultAnchor(kind));
  const [branch, setBranch] = useState(""); const [program, setProgram] = useState(""); const [person, setPerson] = useState("");
  const [report, setReport] = useState<Report | null>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(true); const pending = useRef<AbortController | null>(null);
  async function load() { pending.current?.abort(); const controller = new AbortController(); pending.current = controller; setBusy(true); setError(""); try { const [from, to] = range(kind, anchor); const query = new URLSearchParams({ from, to, branch, program, person }); const response = await fetch(`/api/reports?${query}`, { cache: "no-store", signal: controller.signal }); const result = await response.json(); if (!response.ok || !result.success) throw new Error(result.message || "Unable to generate report."); if (!controller.signal.aborted) setReport(result.report); } catch (failure) { if (!controller.signal.aborted) setError(failure instanceof Error ? failure.message : "Unable to generate report."); } finally { if (!controller.signal.aborted) setBusy(false); } }
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => { window.clearTimeout(timer); pending.current?.abort(); }; // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);
  const periodRows = useMemo(() => { if (!report) return []; if (kind === "daily" || kind === "weekly") return report.byDay.map((line) => ({ label: line.date, ...line })); const groups = new Map<string, Line & { label: string }>(); for (const line of report.byDay) { const label = kind === "yearly" ? line.date.slice(0, 7) : `Week ${Math.ceil(Number(line.date.slice(8, 10)) / 7)}`; const current = groups.get(label); if (!current) groups.set(label, { ...line, label }); else for (const key of ["accounts", "gross", "incentives", "fidelity", "net", "expectedRemittance"] as const) current[key] += line[key]; } return [...groups.values()]; }, [report, kind]);
  function exportCsv() { if (!report) return; const rows: unknown[][] = [["Period", "Accounts", "Gross", "Incentives", "Fidelity", "Net", "Expected Remittance"], ...periodRows.map((row) => [row.label, row.accounts, row.gross, row.incentives, row.fidelity, row.net, row.expectedRemittance])]; const url = URL.createObjectURL(new Blob(["\uFEFF" + rows.map((row) => row.map(csv).join(",")).join("\r\n")], { type: "text/csv;charset=utf-8" })); const link = document.createElement("a"); link.href = url; link.download = `${kind}-report-${report.from}-${report.to}.csv`; link.click(); URL.revokeObjectURL(url); }
  const title = `${kind[0].toUpperCase()}${kind.slice(1)} Report`;
  return <section className="min-w-0 space-y-6"><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0"><h1 className="text-2xl font-bold">{title}</h1><p className="text-sm text-muted-foreground">Calculated from source Sales, Collections, Remittances, Expenses, and Deposit records.</p></div><div className="flex w-full flex-wrap gap-2 print:hidden sm:w-auto"><Button className="flex-1 sm:flex-none" variant="outline" disabled={!report} onClick={() => window.print()}>Print</Button><Button className="flex-1 sm:flex-none" variant="outline" disabled={!report} onClick={exportCsv}>Export Excel</Button></div></div>
    <div className="grid gap-3 rounded-xl border bg-background p-4 sm:grid-cols-2 lg:grid-cols-5 print:hidden"><label className="text-sm">Period<input className="mt-1 block w-full rounded-md border bg-background p-2" type={inputType(kind)} min={kind === "yearly" ? "2000" : undefined} max={kind === "yearly" ? "2100" : undefined} value={anchor} onChange={(event) => setAnchor(event.target.value)}/></label><Filter label="Branch" value={branch} values={report?.options.branches ?? []} onChange={setBranch}/><label className="text-sm">Program<select className="mt-1 block w-full rounded-md border bg-background p-2" value={program} onChange={(event) => setProgram(event.target.value)}><option value="">All</option>{report?.options.programs.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><Filter label="MAS / Collector" value={person} values={report?.options.people ?? []} onChange={setPerson}/><div className="flex items-end"><Button disabled={busy || !anchor} onClick={() => void load()}>{busy ? "Generating..." : "View report"}</Button></div></div>
    {error && <p role="alert" className="text-destructive">{error}</p>}{report && <p className="text-sm text-muted-foreground">Period: {report.from} to {report.to} · Generated by {report.generatedBy} on {new Date(report.generatedAt).toLocaleString("en-PH")}</p>}
    {report && <><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Accounts", report.summary.accounts], ["Gross", money(report.summary.gross)], ["Incentives", money(report.summary.incentives)], ["Net before expenses", money(report.summary.net)], ["Expenses", money(report.summary.expenses)], ["Expected remittance", money(report.summary.expectedRemittance)], ["Actual approved remittance", money(report.summary.actualRemittance)], ["Difference", money(report.summary.difference)]].map(([label, value]) => <div key={label} className="rounded-xl border bg-background p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-2 text-xl font-semibold">{value}</p></div>)}</div>
      {kind === "daily" ? <><ReportTable title="New Sales" rows={report.sales}/><ReportTable title="Collections" rows={report.collections}/></> : <ReportTable title={kind === "weekly" ? "Daily Breakdown" : kind === "monthly" ? "Weekly Breakdown" : "Monthly Breakdown"} rows={periodRows}/>}<ReportTable title="Branch Performance" rows={report.byBranch} label="branch"/><ReportTable title="Program Performance" rows={report.byProgram} label="programName"/>
      <div className="rounded-xl border bg-muted/20 p-4"><h2 className="font-semibold">Reconciliation</h2><dl className="mt-3 grid gap-2 text-sm sm:grid-cols-2">{[["Gross", report.summary.gross], ["Less incentives", -report.summary.incentives], ["Less fidelity", -report.summary.fidelity], ["Less expenses", -report.summary.expenses], ["Expected remittance", report.summary.expectedRemittance], ["Actual approved remittance", report.summary.actualRemittance], ["Deposits", report.summary.deposits], ["Difference", report.summary.difference]].map(([label, value]) => <div key={label} className="flex justify-between border-b py-2"><dt>{label}</dt><dd>{money(Number(value))}</dd></div>)}</dl></div>{report.notes.map((note) => <p key={note} className="text-xs text-amber-700">{note}</p>)}</>}
  </section>;
}

function Filter({ label, value, values, onChange }: { label: string; value: string; values: string[]; onChange: (value: string) => void }) { return <label className="text-sm">{label}<select className="mt-1 block w-full rounded-md border bg-background p-2" value={value} onChange={(event) => onChange(event.target.value)}><option value="">All</option>{values.map((item) => <option key={item}>{item}</option>)}</select></label>; }
function ReportTable({ title, rows, label = "date" }: { title: string; rows: Array<Line & { label?: string }>; label?: keyof Line }) { const transactionTable = title === "New Sales" || title === "Collections"; return <section className="overflow-hidden rounded-xl border bg-background"><h2 className="border-b bg-muted/30 p-4 font-semibold">{title}</h2><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{[transactionTable ? "Name / Details" : "Period", "Accounts", "Gross", "Incentives", "Fidelity", "Net", "Expected Remittance"].map((heading) => <th key={heading} className="p-3">{heading}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={`${row.date}-${row.branch}-${row.programId}-${row.person}-${index}`} className="border-t"><td className="p-3">{transactionTable ? row.person || "Unassigned" : row.label || String(row[label] || row.date)}<span className="block text-xs text-muted-foreground">{transactionTable ? `${row.date} · ${row.programName || "No program"} · ${row.branch || "No branch"}${row.role ? ` · ${row.role}` : ""}` : row.person && row.role ? `${row.person} · ${row.role}` : ""}</span></td><td className="p-3">{row.accounts}</td><td className="p-3">{money(row.gross)}</td><td className="p-3">{money(row.incentives)}</td><td className="p-3">{money(row.fidelity)}</td><td className="p-3">{money(row.net)}</td><td className="p-3">{money(row.expectedRemittance)}</td></tr>)}{!rows.length && <tr><td colSpan={7} className="p-8 text-center text-muted-foreground">No transactions in this period.</td></tr>}</tbody></table></div></section>; }
