import { GOOGLE_SHEET_ID, sheets } from "@/lib/google-sheets";
import { getEncoder } from "@/lib/encoder-context";

const text = (value: unknown) => String(value ?? "").trim();
const bool = (value: unknown) => ["true", "yes", "1"].includes(text(value).toLowerCase());
export type RoleRecord = { id: string; name: string; description: string; manageUsers: boolean; manageAttendance: boolean; viewAttendanceReports: boolean; status: "active" | "inactive" };

async function data() { return (await sheets.spreadsheets.values.get({ spreadsheetId: GOOGLE_SHEET_ID, range: "Roles!A:K" })).data.values ?? []; }
export async function getRoles(): Promise<RoleRecord[]> { const rows = await data(); const ids = new Set<string>(); return rows.slice(1).filter((row) => text(row[0])).map((row) => { const id = text(row[0]); if (ids.has(id)) throw new Error(`Duplicate role ID ${id}. Run the roles migration.`); ids.add(id); return { id, name: text(row[1]), description: text(row[2]), manageUsers: bool(row[3]), manageAttendance: bool(row[4]), viewAttendanceReports: bool(row[5]), status: text(row[6]).toLowerCase() === "inactive" ? "inactive" : "active" }; }); }
function input(value: Partial<RoleRecord>) { const name = text(value.name); if (!name || name.length > 80) throw new Error("Enter a unique role name of up to 80 characters."); return { name, description: text(value.description), manageUsers: Boolean(value.manageUsers), manageAttendance: Boolean(value.manageAttendance), viewAttendanceReports: Boolean(value.viewAttendanceReports), status: value.status === "inactive" ? "inactive" as const : "active" as const }; }
export async function createRole(value: Partial<RoleRecord>) { const role = input(value), roles = await getRoles(); if (roles.some((item) => item.name.toLowerCase() === role.name.toLowerCase())) throw new Error("That role name already exists."); const actor = getEncoder(), id = `ROLE-${crypto.randomUUID()}`; await sheets.spreadsheets.values.append({ spreadsheetId: GOOGLE_SHEET_ID, range: "Roles!A:K", valueInputOption: "RAW", insertDataOption: "INSERT_ROWS", requestBody: { values: [[id, role.name, role.description, role.manageUsers, role.manageAttendance, role.viewAttendanceReports, role.status, actor.userId, actor.employeeId, actor.username, actor.encodedAt]] } }); return { id, ...role }; }
export async function updateRole(id: string, value: Partial<RoleRecord>) { const role = input(value), rows = await data(), rowIndex = rows.slice(1).findIndex((row) => text(row[0]) === id); if (rowIndex < 0) throw new Error("Role not found."); if (rows.slice(1).some((row, index) => index !== rowIndex && text(row[1]).toLowerCase() === role.name.toLowerCase())) throw new Error("That role name already exists."); await sheets.spreadsheets.values.update({ spreadsheetId: GOOGLE_SHEET_ID, range: `Roles!B${rowIndex + 2}:G${rowIndex + 2}`, valueInputOption: "RAW", requestBody: { values: [[role.name, role.description, role.manageUsers, role.manageAttendance, role.viewAttendanceReports, role.status]] } }); return { id, ...role }; }
export async function deleteRole(id: string) { const [roles, links] = await Promise.all([data(), sheets.spreadsheets.values.get({ spreadsheetId: GOOGLE_SHEET_ID, range: "'User Roles'!A:B" })]); if ((links.data.values ?? []).slice(1).some((row) => text(row[1]) === id)) throw new Error("This role is assigned to user accounts. Remove those assignments or set the role inactive."); const rowIndex = roles.slice(1).findIndex((row) => text(row[0]) === id); if (rowIndex < 0) throw new Error("Role not found."); await sheets.spreadsheets.values.update({ spreadsheetId: GOOGLE_SHEET_ID, range: `Roles!A${rowIndex + 2}:K${rowIndex + 2}`, valueInputOption: "RAW", requestBody: { values: [Array(11).fill("")] } }); }
