import { canManageAccounts } from "@/lib/auth-server";
import { withEncoder } from "@/lib/encoder-context";
import { guardRoleChange } from "@/lib/privilege-guard";
import { createRole, deleteRole, getRoles, updateRole } from "@/lib/roles";

const refuse = (message: string) => Response.json({ success: false, message }, { status: 403 });
export async function GET() { if (!(await canManageAccounts())) return Response.json({ success: false, message: "Administrator access is required." }, { status: 403 }); try { return Response.json({ success: true, roles: await getRoles() }); } catch (error) { return Response.json({ success: false, message: error instanceof Error ? error.message : "Unable to load roles." }, { status: 500 }); } }
export const POST = withEncoder(async (request: Request) => { if (!(await canManageAccounts())) return Response.json({ success: false, message: "Administrator access is required." }, { status: 403 }); try { const body = await request.json(); const denied = await guardRoleChange({ name: body.name, manageUsers: body.manageUsers }); if (denied) return refuse(denied); return Response.json({ success: true, role: await createRole(body) }, { status: 201 }); } catch (error) { return Response.json({ success: false, message: error instanceof Error ? error.message : "Unable to create role." }, { status: 400 }); } });
export const PATCH = withEncoder(async (request: Request) => { if (!(await canManageAccounts())) return Response.json({ success: false, message: "Administrator access is required." }, { status: 403 }); try { const body = await request.json(); const denied = await guardRoleChange({ roleId: String(body.id ?? ""), name: body.name, manageUsers: body.manageUsers }); if (denied) return refuse(denied); return Response.json({ success: true, role: await updateRole(String(body.id ?? ""), body) }); } catch (error) { return Response.json({ success: false, message: error instanceof Error ? error.message : "Unable to update role." }, { status: 400 }); } });
export const DELETE = withEncoder(async (request: Request) => { if (!(await canManageAccounts())) return Response.json({ success: false, message: "Administrator access is required." }, { status: 403 }); try { const id = String((await request.json()).id ?? ""); const denied = await guardRoleChange({ roleId: id }); if (denied) return refuse(denied); await deleteRole(id); return Response.json({ success: true }); } catch (error) { return Response.json({ success: false, message: error instanceof Error ? error.message : "Unable to delete role." }, { status: 400 }); } });
