"use client";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { Banknote, CalendarDays, ChevronDown, Filter, Paperclip, Plus, Receipt, RefreshCw, XCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { SearchSelect } from "@/components/ui/search-select";
import { EXPENSE_ACCOUNTS, EXPENSE_APPROVERS, EXPENSE_ATTACHMENTS } from "@/lib/expense-options";
import { useLiveRefresh } from "@/lib/use-live-refresh";
type Expense = { id:string; date:string; category:string; description:string; amount:number; payee:string; paidBy:string; branch:string; paymentMethod:string; referenceNumber:string; receiptNumber:string; status:string; remarks:string; voidReason:string; attachments:string; approvedBy:string };
type Form = { branch:string; date:string; category:string; categoryOther:string; amount:string; attachments:string[]; attachmentOther:string; receiptNumber:string; description:string; approvedBy:string; approvedByOther:string; remarks:string; payee:string; paidBy:string; paymentMethod:string; referenceNumber:string };
const today=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Manila"}).format(new Date());
const empty=():Form=>({branch:"",date:today(),category:"",categoryOther:"",amount:"",attachments:[],attachmentOther:"",receiptNumber:"",description:"",approvedBy:"",approvedByOther:"",remarks:"",payee:"",paidBy:"Cash on Hand",paymentMethod:"Cash",referenceNumber:""});
const money=(v:number)=>new Intl.NumberFormat("en-PH",{style:"currency",currency:"PHP"}).format(v);
const selectClass="h-9 w-full rounded-md border bg-background px-3 text-sm";
// Saved "Other: detail" values group under "Other" in the account filter.
const accountOf=(category:string)=>category.startsWith("Other:")?"Other":category;

export default function ExpensesPage(){
 const [financeBranches,setFinanceBranches]=useState<Array<{id:string;name:string;territory:string}>>([]),[cashAccounts,setCashAccounts]=useState<Array<{id:string;name:string;status:string}>>([]);
 const [expenses,setExpenses]=useState<Expense[]>([]),[canVoid,setCanVoid]=useState(false),[form,setForm]=useState<Form>(empty),[showForm,setShowForm]=useState(false),[showPayment,setShowPayment]=useState(false),[busy,setBusy]=useState(true),[message,setMessage]=useState(""),[error,setError]=useState(""),[search,setSearch]=useState(""),[branch,setBranch]=useState(""),[account,setAccount]=useState(""),[status,setStatus]=useState("");
 const load=useCallback(async()=>{setBusy(true);setError("");try{const [r,o]=await Promise.all([fetch("/api/expenses",{cache:"no-store"}),fetch("/api/finance-options",{cache:"no-store"})]);const [j,options]=await Promise.all([r.json(),o.json()]);if(!r.ok)throw new Error(j.message);if(!o.ok)throw new Error(options.message);setExpenses(j.expenses??[]);setCanVoid(Boolean(j.canVoid));setFinanceBranches(options.branches??[]);setCashAccounts(options.accounts??[]);}catch(e){setError(e instanceof Error?e.message:"Unable to load expenses.");}finally{setBusy(false);}},[]);
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{void load();},[load]);
 useLiveRefresh(["expenses"], load); // live updates (lib/use-live-refresh.ts)
 const rows=useMemo(()=>expenses.filter(x=>(!branch||x.branch===branch)&&(!account||accountOf(x.category)===account)&&(!status||x.status===status)&&`${x.description} ${x.category} ${x.payee} ${x.receiptNumber} ${x.referenceNumber} ${x.approvedBy} ${x.id}`.toLowerCase().includes(search.toLowerCase())),[expenses,branch,account,status,search]);
 const posted=useMemo(()=>rows.filter(x=>x.status==="Posted"),[rows]),total=posted.reduce((s,x)=>s+x.amount,0),set=(k:keyof Form,v:string)=>setForm(c=>({...c,[k]:v}));
 // Posted totals per account for the current filters, largest first.
 const byAccount=useMemo(()=>[...posted.reduce((map,x)=>map.set(accountOf(x.category),(map.get(accountOf(x.category))??0)+x.amount),new Map<string,number>())].sort((a,b)=>b[1]-a[1]),[posted]);
 const toggleAttachment=(value:string)=>setForm(c=>({...c,attachments:c.attachments.includes(value)?c.attachments.filter(x=>x!==value):[...c.attachments,value]}));
 async function save(e:FormEvent){e.preventDefault();setBusy(true);setError("");setMessage("");try{const r=await fetch("/api/expenses",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,amount:Number(form.amount)})});const j=await r.json();if(!r.ok)throw new Error(j.message);setForm(empty());setShowForm(false);setShowPayment(false);setMessage(`Expense ${j.id} posted.`);await load();}catch(x){setError(x instanceof Error?x.message:"Unable to save expense.");}finally{setBusy(false);}}
 async function voidRecord(id:string){const reason=window.prompt("Reason for voiding this expense:");if(!reason?.trim())return;setBusy(true);try{const r=await fetch("/api/expenses",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,reason})});const j=await r.json();if(!r.ok)throw new Error(j.message);setMessage(`${id} voided.`);await load();}catch(x){setError(x instanceof Error?x.message:"Unable to void expense.");}finally{setBusy(false);}}
 return <section className="mx-auto max-w-7xl space-y-6"><header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><span className="rounded-md bg-purple-95 px-2 py-1 text-[11px] font-bold uppercase tracking-wider text-purple-60">Finance</span><h1 className="mt-2 text-3xl font-black tracking-tight text-violet-10">Expense Register</h1><p className="text-sm text-violet-40">Record branch expenses by account, with the supporting documents and who approved them.</p></div><div className="flex gap-2"><Button variant="outline" onClick={()=>void load()} disabled={busy}><RefreshCw className={`size-4 ${busy?"animate-spin":""}`}/>Refresh</Button><Button onClick={()=>setShowForm(v=>!v)}><Plus className="size-4"/>Add Expense</Button></div></header>
 {error&&<p role="alert" className="rounded-xl border border-destructive/30 bg-destructive/10 p-3 text-sm text-destructive">{error}</p>}{message&&<p role="status" className="rounded-xl border border-accent-lime/50 bg-accent-lime/15 p-3 text-sm text-accent-moss">{message}</p>}
 <div className="grid gap-4 sm:grid-cols-3"><Metric icon={<Banknote/>} label="Posted expenses" value={money(total)}/><Metric icon={<Receipt/>} label="Posted entries" value={String(posted.length)}/><Metric icon={<CalendarDays/>} label="Largest account" value={byAccount[0]?`${byAccount[0][0]} · ${money(byAccount[0][1])}`:"—"}/></div>
 {showForm&&<Card className="rounded-3xl"><CardHeader><CardTitle>New Expense</CardTitle></CardHeader><CardContent><form onSubmit={save} className="space-y-5">
  <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
   <Field label="Branch *"><SearchSelect aria-label="Branch" className="h-9" placeholder="Search branch" value={form.branch} onValueChange={value=>set("branch",value)} options={financeBranches.map(x=>({value:x.name,label:x.name,description:x.territory}))}/></Field>
   <Field label="Date of expense *"><Input type="date" required max={today()} value={form.date} onChange={e=>set("date",e.target.value)}/></Field>
   <Field label="Account name *"><select required className={selectClass} value={form.category} onChange={e=>set("category",e.target.value)}><option value="">Select account</option>{EXPENSE_ACCOUNTS.map(x=><option key={x}>{x}</option>)}</select></Field>
   <Field label="Amount *"><Input type="number" required min="0.01" step="0.01" value={form.amount} onChange={e=>set("amount",e.target.value)}/></Field>
   {form.category==="Other"&&<Field label="Specify account *"><Input required maxLength={100} value={form.categoryOther} onChange={e=>set("categoryOther",e.target.value)}/></Field>}
   <Field label="Invoice / Receipt No."><Input value={form.receiptNumber} onChange={e=>set("receiptNumber",e.target.value)}/></Field>
   <Field label="Approved by *"><select required className={selectClass} value={form.approvedBy} onChange={e=>set("approvedBy",e.target.value)}><option value="">Select approver</option>{EXPENSE_APPROVERS.map(x=><option key={x}>{x}</option>)}</select></Field>
   {form.approvedBy==="Other"&&<Field label="Approver name *"><Input required maxLength={100} value={form.approvedByOther} onChange={e=>set("approvedByOther",e.target.value)}/></Field>}
  </div>
  <fieldset className="rounded-xl border p-3"><legend className="flex items-center gap-1 px-1 text-sm font-medium"><Paperclip className="size-3.5"/>Attachments</legend><div className="flex flex-wrap gap-x-5 gap-y-2">{EXPENSE_ATTACHMENTS.map(x=><label key={x} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.attachments.includes(x)} onChange={()=>toggleAttachment(x)}/>{x}</label>)}</div>{form.attachments.includes("Other")&&<div className="mt-3 max-w-sm"><Field label="Specify other attachment *"><Input required maxLength={100} value={form.attachmentOther} onChange={e=>set("attachmentOther",e.target.value)}/></Field></div>}<p className="mt-2 text-xs text-muted-foreground">Tick the documents that support this expense.</p></fieldset>
  <div className="grid gap-4 md:grid-cols-2"><Field label="Purpose *"><Input required value={form.description} onChange={e=>set("description",e.target.value)}/></Field><Field label="Remarks / notes"><Input value={form.remarks} onChange={e=>set("remarks",e.target.value)}/></Field></div>
  <div className="rounded-xl border"><button type="button" aria-expanded={showPayment} onClick={()=>setShowPayment(v=>!v)} className="flex w-full items-center justify-between p-3 text-sm font-medium"><span>Payment details <span className="font-normal text-muted-foreground">(optional · paid from {form.paidBy||"Cash on Hand"} in {form.paymentMethod||"Cash"})</span></span><ChevronDown className={`size-4 transition-transform ${showPayment?"rotate-180":""}`}/></button>
   {showPayment&&<div className="grid gap-4 border-t p-3 md:grid-cols-2 lg:grid-cols-4"><Field label="Paid from"><select className={selectClass} value={form.paidBy} onChange={e=>set("paidBy",e.target.value)}><option value="">Select cash account</option>{cashAccounts.filter(x=>x.status==="active").map(x=><option key={x.id}>{x.name}</option>)}</select></Field><Field label="Payment method"><select className={selectClass} value={form.paymentMethod} onChange={e=>set("paymentMethod",e.target.value)}>{["Cash","Bank Transfer","Check","E-wallet"].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Payee"><Input value={form.payee} onChange={e=>set("payee",e.target.value)}/></Field><Field label="Payment reference"><Input value={form.referenceNumber} onChange={e=>set("referenceNumber",e.target.value)}/></Field></div>}
  </div>
  <div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={()=>setShowForm(false)}>Cancel</Button><Button type="submit" disabled={busy||!form.branch}>Post Expense</Button></div>
 </form></CardContent></Card>}
 {byAccount.length>0&&<Card className="rounded-3xl"><CardHeader><CardTitle>Posted by Account</CardTitle></CardHeader><CardContent><ul className="space-y-2">{byAccount.map(([name,amount])=><li key={name} className="grid grid-cols-[10rem_minmax(0,1fr)_auto] items-center gap-3 text-sm"><button type="button" onClick={()=>setAccount(account===name?"":name)} className={`truncate text-left ${account===name?"font-bold text-primary":""}`}>{name}</button><span className="h-2 overflow-hidden rounded-full bg-muted"><span className="block h-full rounded-full bg-primary" style={{width:`${(amount/byAccount[0][1])*100}%`}}/></span><span className="font-semibold tabular-nums">{money(amount)}</span></li>)}</ul></CardContent></Card>}
 <Card className="rounded-3xl"><CardHeader><CardTitle className="flex items-center gap-2"><Filter className="size-4 text-violet-60"/>Expense Register</CardTitle></CardHeader><CardContent className="space-y-4"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Input placeholder="Search purpose, receipt no., approver..." value={search} onChange={e=>setSearch(e.target.value)}/><SearchSelect aria-label="Branch" className="h-9" clearable placeholder="All branches" value={branch} onValueChange={setBranch} options={[...new Set(expenses.map(x=>x.branch))].filter(Boolean).sort().map(x=>({value:x,label:x}))}/><select aria-label="Account" className={selectClass} value={account} onChange={e=>setAccount(e.target.value)}><option value="">All accounts</option>{[...new Set([...EXPENSE_ACCOUNTS,...expenses.map(x=>accountOf(x.category))])].filter(Boolean).map(x=><option key={x}>{x}</option>)}</select><select aria-label="Status" className={selectClass} value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option><option>Posted</option><option>Voided</option></select></div>
  <div className="overflow-x-auto rounded-xl border"><table className="w-full min-w-[1080px] text-sm"><thead className="bg-violet-95/60 text-left text-xs uppercase text-violet-40"><tr>{["Date","Branch","Account / Purpose","Invoice / Receipt","Attachments","Approved by","Amount","Status","Action"].map(h=><th key={h} className="p-3">{h}</th>)}</tr></thead><tbody>{rows.map(x=><tr key={x.id} className="border-t align-top"><td className="p-3 whitespace-nowrap">{x.date}</td><td className="p-3">{x.branch}</td><td className="p-3"><p className="font-semibold">{x.category}</p><p className="text-xs text-muted-foreground">{x.description}</p>{x.remarks&&<p className="text-xs text-muted-foreground">Note: {x.remarks}</p>}<p className="text-[11px] text-muted-foreground">{x.id}</p></td><td className="p-3">{x.receiptNumber||x.referenceNumber||"—"}</td><td className="p-3">{x.attachments?<div className="flex flex-wrap gap-1">{x.attachments.split(", ").map(a=><span key={a} className="rounded-full border px-2 py-0.5 text-xs">{a}</span>)}</div>:<span className="text-xs text-muted-foreground">None recorded</span>}</td><td className="p-3">{x.approvedBy||<span className="text-xs text-muted-foreground">Not recorded</span>}</td><td className="p-3 font-bold tabular-nums">{money(x.amount)}</td><td className="p-3"><span className={`rounded-full px-2 py-1 text-xs font-bold ${x.status==="Voided"?"bg-rose-100 text-rose-700":"bg-accent-lime/20 text-accent-moss"}`}>{x.status}</span>{x.voidReason&&<p className="mt-1 text-xs text-muted-foreground">{x.voidReason}</p>}</td><td className="p-3">{canVoid&&x.status==="Posted"&&<Button size="sm" variant="ghost" onClick={()=>void voidRecord(x.id)}><XCircle className="size-4"/>Void</Button>}</td></tr>)}{!rows.length&&<tr><td colSpan={9} className="p-10 text-center text-muted-foreground">No expenses match the filters.</td></tr>}</tbody></table></div></CardContent></Card></section>;
}
function Metric({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <Card className="rounded-2xl"><CardContent className="pt-5"><div className="mb-3 flex size-9 items-center justify-center rounded-xl bg-violet-95 text-violet-60 [&>svg]:size-4">{icon}</div><p className="text-xs text-violet-40">{label}</p><p className="mt-1 text-2xl font-black text-violet-10">{value}</p></CardContent></Card>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="space-y-2"><Label>{label}</Label>{children}</div>}
